version: "3.8"

services:
  fyp_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata:
